### PR TITLE
Update config.cfg

### PR DESCRIPTION
**Pull request by Yecgaa1**
I think this version of cfg is better than last one

### CODE REVIEW

**Comment by ClaudeMetz** [comment]
Yeah this is way more complete, thanks a lot! (You're the one that did the first Chinese translation right? Sorry about not accepting your word then, I'm happy you found your way here now.)

I'm not sure yet when the next update will be released, but it will include your work.

**Comment by Yecgaa1** [comment]
No,this cfg is traslated by  the name is "尐风﹏" person , I just adjust his a little word and upload to you,I hope this mod will have a native official translate, thank you give this chance to us, I hope I can keep in repairing this cfg,but now my factorio base version is 1.17(which is steam only allow me to download),not the bate 1.18. I also hope you can republish the mod with translation for base version 1.17.

**Comment by ClaudeMetz** [comment]
Oh okay, that's cool too. The 0.18 version of the mod has been updated with this translation today.
I'm not sure if I will update the 0.17 version too, I'm sorry about that. You can get the 0.18 version on Steam too, if you want. Take a look at a guide like [this one](https://steamcommunity.com/app/427520/discussions/0/359547436748424896/).

**Comment by tvardero** [comment]
To translate info.json file (title and description of the mod on the Mod Portal), add those lines to config.cfg:
```
[mod-name]
factoryplanner=Factory Planner (_title_in_your_language_)

[mod-description]
factoryplanner=_description_in_your_language_
```

**Pull request merged**
